#!/bin/bash
SERVICE_FILE="/etc/systemd/system/ngrok.service"

curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
	| sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
	&& echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
	| sudo tee /etc/apt/sources.list.d/ngrok.list \
	&& sudo apt update \
	&& sudo apt install ngrok

ngrok config add-authtoken 2aM5moVsRxtpqDnyN9pRpiS3HAK_7Kh9msFusXx5Af4GSJGYj


# Create systemd service for ngrok
echo "Setting up ngrok as a service..."
cat > $SERVICE_FILE <<EOL
[Unit]
Description=Ngrok SSH Tunnel Service
After=network.target

[Service]
ExecStart=/usr/bin/ngrok tcp 22
Restart=on-failure

[Install]
WantedBy=multi-user.target

EOL

# Enable and start the ngrok service
echo "Enabling and starting the ngrok service..."
systemctl enable ngrok
systemctl start ngrok

# Confirm setup
systemctl status ngrok --no-pager

echo "Setup complete. Ngrok is now running and exposing port 22 (SSH) on TCP."
